export type IgnoreTemplateName = "nodepython";

export function defaultIgnore(template: IgnoreTemplateName, opts?: { ignoreGit?: boolean }): string[] {
  if (template !== "nodepython") throw new Error(`Unknown template: ${template}`);

  const lines: string[] = [
    "# OS / Editor",
    ".DS_Store",
    "Thumbs.db",
    "*.swp",
    "*.swo",
    ".idea/",
    ".vscode/",
    "*.iml",
    "",
    "# Logs",
    "*.log",
    "npm-debug.log*",
    "yarn-debug.log*",
    "yarn-error.log*",
    "pnpm-debug.log*",
    "",
    "# Node",
    "node_modules/",
    ".pnp/",
    ".pnp.cjs",
    ".yarn/cache/",
    ".yarn/unplugged/",
    ".yarn/build-state.yml",
    ".yarn/install-state.gz",
    "",
    "# Next/React build outputs",
    ".next/",
    "out/",
    "dist/",
    "build/",
    "coverage/",
    ".turbo/",
    ".vercel/",
    ".parcel-cache/",
    ".eslintcache",
    "*.tsbuildinfo",
    "",
    "# Python",
    "__pycache__/",
    "*.py[cod]",
    ".pytest_cache/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".coverage",
    "coverage.xml",
    "htmlcov/",
    ".tox/",
    ".nox/",
    ".ipynb_checkpoints/",
    "",
    "# Virtualenvs (uv/venv)",
    ".venv/",
    "venv/",
    "ENV/",
    "env/",
    "",
    "# uv caches (best effort)",
    ".uv/",
    "uv-cache/",
    "**/.uv-cache/",
    "",
    "# Misc caches",
    ".cache/",
    "tmp/",
    "temp/",
  ];

  if (opts?.ignoreGit) {
    lines.push("", "# Optional", ".git/");
  }

  return lines;
}
